import 'dart:convert';

// Mock ExportService for generating CSV or PDF payloads.
class ExportService {
  static String generateCsv(List<Map<String, dynamic>> rows) {
    if (rows.isEmpty) return '';
    final headers = rows.first.keys.toList();
    final buffer = StringBuffer();
    buffer.writeln(headers.join(','));
    for (final r in rows) {
      buffer.writeln(headers.map((h) => r[h]).join(','));
    }
    return buffer.toString();
  }

  static List<int> generatePdfPlaceholder(String title, String content) {
    // Placeholder: return UTF8 bytes – replace with real PDF in future.
    final text = 'PDF REPORT\n$title\n\n$content\n-- Generated by ClinAlert --';
    return utf8.encode(text);
  }
}


